services:
  database:
    image: mongo:latest
    container_name: lazygarden-db
    restart: always
    ports:
      - "27099:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dev
      - MONGO_INITDB_ROOT_PASSWORD=dev1234
      - MONGO_INITDB_DATABASE=lazygarden